name: CI

on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        nim-version: [ "binary:2.0.0", "binary:2.0.2" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # - name: Install nim
      #   uses: iffy/install-nim@v4
      #   with:
      #     version: binary:2.0.2

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '2.0.2' # default is 'stable'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: nimble -d:ssl test
