name: CI

on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        nim-version: [ "2.0.0", "2.0.2" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit tests
        run: nimble unittests

      - name: Run integation tests
        # go-httpbin container does not run on windows runner for some reason. macos runner does not has docker by default
        if: ${{ matrix.os == 'ubuntu-latest' }} 
        run: nimble inttests
