name: CI

on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install nim
        uses: iffy/install-nim@v4
        with:
          version: binary:2.0.0

      - name: Test
        run: nimble -d:ssl test
